repos:
  # General pre-commit hooks for common issues
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast

  # Black formatter for consistent code style
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3.12 # Specify your Python version
        files: ^(swiftnomads/|tests/)$

  # Flake8 linter for style guide enforcement and error checking
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0 # Use the latest stable version
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        files: ^(swiftnomads/|tests/)

  # isort for sorting imports alphabetically and separating them into sections
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1 # Use the latest stable version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"] # Use the black profile for compatibility
        files: ^(swiftnomads/|tests/)
