from __future__ import absolute_import

from .gfs import (
    GFSConfig,
    build_gfs_reference_metadata,
    build_gfs_refs,
    default_gfs_cache_path,
    get_or_build_gfs_refs,
    list_gfs_forecast_hours,
    list_reference_groups,
    load_kerchunk_refs,
    load_reference_metadata,
    open_gfs_dataset,
    open_gfs_dataset_cached,
    save_kerchunk_refs,
    save_reference_metadata,
    should_refresh_gfs_reference,
)
from .models import (
    ModelAdapter,
    available_models,
    get_model_adapter,
    infer_model_config,
    open_model_dataset_cached,
)
from .rtofs import (
    RTOFSConfig,
    build_rtofs_refs,
    default_rtofs_cache_path,
    get_or_build_rtofs_refs,
    list_rtofs_forecast_hours,
    open_rtofs_dataset,
    open_rtofs_dataset_cached,
    rtofs_reference_url,
    should_refresh_rtofs_reference,
)

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = ""


__all__ = [
    "__version__",
    "GFSConfig",
    "build_gfs_refs",
    "build_gfs_reference_metadata",
    "default_gfs_cache_path",
    "get_or_build_gfs_refs",
    "list_gfs_forecast_hours",
    "list_reference_groups",
    "load_kerchunk_refs",
    "load_reference_metadata",
    "open_gfs_dataset",
    "open_gfs_dataset_cached",
    "save_kerchunk_refs",
    "save_reference_metadata",
    "should_refresh_gfs_reference",
    "RTOFSConfig",
    "rtofs_reference_url",
    "list_rtofs_forecast_hours",
    "build_rtofs_refs",
    "default_rtofs_cache_path",
    "should_refresh_rtofs_reference",
    "get_or_build_rtofs_refs",
    "open_rtofs_dataset",
    "open_rtofs_dataset_cached",
    "ModelAdapter",
    "available_models",
    "get_model_adapter",
    "infer_model_config",
    "open_model_dataset_cached",
]
